#!/usr/bin/env bash

REPO="$(git rev-parse --show-toplevel)"

ALIENPY_IS_CHANGED=$(git status -s ${REPO}/alienpy/alien.py)
[[ -n "${ALIENPY_IS_CHANGED}" ]] && touch ${REPO}/.commit_in_progress

exit 0

