#!/usr/bin/env bash

[[ ! -e alienpy/alien.py ]] && { echo "alien.py was not found"; exit 1; }

./update_version
git commit -m "alien.py update version info" alienpy/alien.py

git tag $(< VERSION)
git push --tags
git push --tags xjalienfs master

#tag=$(git describe --tags --abbrev=0 --exact-match)

mkdir -p dist
rm -rf dist/*
python3 setup.py sdist bdist_wheel

