#!/usr/bin/env bash

[[ ! -e alienpy/alien.py ]] && { echo "alien.py was not found"; exit 1; }

tag=$(git describe --tags --abbrev=0 --exact-match)
[[ -n ${tag} ]] && echo ${tag} >> ./VERSION

./update_version
git commit -m "alien.py update version info" alienpy/alien.py

mkdir -p dist
rm -rf dist/*
python3 setup.py sdist bdist_wheel

