#!/usr/bin/env bash

VENV_DIR="alienpy_test_env_no_xrootd"

rm -rf "${VENV_DIR}"
mkdir -p "${VENV_DIR}"
python3 -m venv "${VENV_DIR}" || { echo "error"; exit 1; }

source "${VENV_DIR}/bin/activate"

ALIBUILD=1 pip install -e .

alien.py version
ECODE="${?}"
echo "version Exit code = ${ECODE}"

alien-token-info >& /dev/null
ECODE="${?}"
echo "alien-token-info Exit code = ${ECODE}"

