#!/usr/bin/env bash

VENV_DIR="alienpy_test_env312"

rm -rf "${VENV_DIR}"
mkdir -p "${VENV_DIR}"
python3.12 -m venv "${VENV_DIR}" || { echo "error"; exit 1; }

source "${VENV_DIR}/bin/activate"
pip install --upgrade pip

./install_user_dev

cd tests
./run_tests

