#!/usr/bin/env bash

VENV_DIR="alienpy_test_env_pip_local"

rm -rf "${VENV_DIR}"
mkdir -p "${VENV_DIR}"
python3 -m venv "${VENV_DIR}" || { echo "error"; exit 1; }

source "${VENV_DIR}/bin/activate"
pip install --upgrade pip
pip install --upgrade alienpy

cd tests
./run_tests

