#!/usr/bin/env bash

VENV_DIR="alienpy_test_env314"

rm -rf "${VENV_DIR}"
mkdir -p "${VENV_DIR}"
python3.14 -m venv "${VENV_DIR}" || { echo "error"; exit 1; }

source "${VENV_DIR}/bin/activate"
pip install --no-cache-dir --upgrade pip setuptools[core] wheel

./install_user_dev

cd tests
./run_tests

