#!/usr/bin/env bash

MYDIR=$(dirname $(realpath -P "${BASH_SOURCE[@]}"))
pushd "${MYDIR}" &> /dev/null
HASH="$(git rev-parse --short --verify HEAD)"

sed -i "/^ALIENPY_VERSION_DATE = /c\ALIENPY_VERSION_DATE = \'$(date -u +%Y%m%d_%H%M%S)\'" alienpy/alien.py
sed -i "/^ALIENPY_VERSION_STR = /c\ALIENPY_VERSION_STR = \'$(< alienpy/VERSION)\'" alienpy/alien.py
sed -i "/^ALIENPY_VERSION_HASH = /c\ALIENPY_VERSION_HASH = \'${HASH}\'" alienpy/alien.py

popd &> /dev/null

