#!/usr/bin/env bash

ARG="${1}"
shift

[[ "${ARG}" == "ci-tests" ]] && IS_CI="1"

SCRIPT_DIR=$(realpath --canonicalize-existing $( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )) #"

test_dirlist=$(find "${SCRIPT_DIR}" -type d -name "*.test" | sort)

for t in ${test_dirlist}; do
    [[ -n "${IS_CI}" && "$(basename ${t})" == "002_env_tokens.test" ]] && continue;

    echo "Running test : $(basename ${t})"
    pushd "${t}" &> /dev/null
    ./test.sh || { echo "Failed test, stopping testing"; break; }
    popd &> /dev/null
    echo -e "END test : $(basename ${t})\n\n"
done

