#!/usr/bin/env bash

SCRIPT_DIR=$(realpath --canonicalize-existing $( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )) #"

test_dirlist=$(find "${SCRIPT_DIR}" -type d -name "*.test" | sort)

for t in ${test_dirlist}; do
    echo "Running test : $(basename ${t})"
    pushd "${t}" &> /dev/null
    ./test.sh
    popd &> /dev/null
    echo -e "END test : $(basename ${t})\n\n"
done

